language: ruby
cache: bundler
sudo: required
services:
 - docker
#install heroku CLI for deployment
before_script:
 - export HOME="/home/travis"
 - curl https://toolbelt.heroku.com/install.sh | sudo sh
# need node to compile assets
 - nvm install 13.1.0
 - nvm alias default 13.1.0
 - nvm use 13.1.0
 - sudo apt-get install -y nodejs
script:
# fix rspec complaints
 - RAILS_ENV=test bundle exec rails assets:precompile
 - RAILS_ENV=test bundle exec rails db:migrate
 - bundle exec rspec spec/
# rubocop tends to think this is valid ruby code
 - sudo rm -r node_modules
 - bundle exec rubocop

after_success:
 - echo "Currently running a $TRAVIS_EVENT_TYPE"
 - if [ $TRAVIS_BRANCH = "ab-continuous-deployment" ]; then export APP="secret-ocean-99829"; elif [ $TRAVIS_BRANCH = "ab-continuous-deployment-multibranch" ]; then export APP="floating-shelf-59360"; fi
 - echo "$APIKEY" | docker login $REGISTRY -u $USERNAME --password-stdin
 - HEROKU_API_KEY="$APIKEY" heroku container:push --app $APP --arg secret=${SECRET} web
 - HEROKU_API_KEY="$APIKEY" heroku container:release --app $APP web